version: '2'

services:
  orderer.example.com:
    image: hyperledger/fabric-orderer:2.5.0
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8000  # Changed to 8000
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./channel-artifacts:/var/hyperledger/orderer
    ports:
      - "8000:7050" 
      - "8003:7053" 

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:2.5.0
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:8001  # Changed to 8001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8001  # Changed to 8001
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:8002  # Changed to 8002
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8001  # Changed to 8001
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8001  # Changed to 8001
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ./peer-artifacts:/var/hyperledger/peer
    ports:
      - "8001:7050" 
      - "8002:7051" 

networks:
  default:
    name: fabric-network
